pipeline {
    agent any 
    parameters {
        choice(name: 'ENV', choices: ['dev', 'prod'], description: 'Select The Environment')
    }
    stages {

            stage('Terraform Init') {
                steps {
                    sh '''
                        cd blueprint
                        terraform init
                    '''
                }
            }
        }           
            stage('Terraform plan') {
                steps {            
                    sh '''
                        cd blueprint
                        terraform plan
                    '''  
                }
            }
        }             
            stage('Terraform Apply') {
                steps {           
                    sh '''
                        cd blueprint   
                        terraform apply
                    '''
                
                           
        }       
    }    
   